name: Scheduled URL Visit


on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: 

jobs:
  ping-url:
    runs-on: ubuntu-latest

    steps:
      - name: Visit the URL using cURL
        run: curl -sL -w "%{http_code}" "https://sentiment-analysis-finbertt.streamlit.app/" -o /dev/null
